import type { User } from '../../domain/entities/User';
import type { Email } from '../../domain/value-objects/Email';

export const USER_REPOSITORY = 'USER_REPOSITORY';

export interface IUserRepository {
  /**
   * Insert or update — the id is generated by the domain, never by the repository.
   *
   * MUST reject with EmailAlreadyUsedError (application/errors/AuthErrors.ts)
   * when the email is already taken, including when two registrations race.
   * RegisterUserUseCase's prior findByEmail() check is a UX shortcut (fail
   * fast, clear error) — it does NOT prevent two concurrent registrations
   * from both passing it. Only a DB-level unique constraint on email, with
   * this method translating its violation into EmailAlreadyUsedError,
   * actually guarantees no duplicate accounts.
   */
  save(user: User): Promise<User>;
  findById(id: string): Promise<User | null>;
  findByEmail(email: Email): Promise<User | null>;
}
