import type { User } from '../../domain/entities/User';
import type { Email } from '../../domain/value-objects/Email';

export const USER_REPOSITORY = 'USER_REPOSITORY';

export interface IUserRepository {
  /** Insert or update — the id is generated by the domain, never by the repository. */
  save(user: User): Promise<User>;
  findById(id: string): Promise<User | null>;
  findByEmail(email: Email): Promise<User | null>;
}
